### ISSUE TITLE
pygame.error: Joystick not initalized 

### ISSUE THREAD

**Issue by dimensions4700** [BrunoTh/ETS2Autopilot#10]
Hi! I've been trying to get this to work for quite a while now :( When I go to set up the keys, everything else registers fine with no errors on my Logitech Driving Force GT wheel. However, when I press 'set' on Steering axis, it spits out an error message in the console. 

`Exception in thread Thread-3:
Traceback (most recent call last):
  File "threading.py", line 914, in _bootstrap_inner
  File "C:\Users\Tyler Thompson\Desktop\ETS2Autopilot-master\UI\thread_joydetection.py", line 42, in run
    if joystick.get_button(i) == 1:
pygame.error: Joystick not initialized`

It registers as "0" in the box when I turn the wheel. When I go to set up the in game stuff, (set kbrd+vjoy as first, wheel as second device) it doesn't register the steering as "Joy Steering...etc." rather, it registers as "Joy 2..." Not sure if you're active on here anymore but it would help. Been interested in this program for a while 😄

**Comment by xmy0916** [comment]
I use paddlepaddle deep learning framework to achieve driverless driving in this game.
It may help you~
https://github.com/xmy0916/EuroTruckSelfDriver @dimensions4700
