### ISSUE TITLE
GUI Setting not detecting Logitech G29 buttons

### ISSUE THREAD

**Issue by MiQ12** [BrunoTh/ETS2Autopilot#11]
When I'm trying to set my controller (Logitech G29 Driving Force) buttons in settings, it won't detect them. It detects the controller but not the buttons. I tried to set the buttons with different joystick (used for flying) and it detected them.
Any help please?

EDIT: Now i got this error in console: E:\Users\User1\Downloads\Autopilot\ETS2Autopilot-master>python\python.exe` start_gui.py
Loading...
Done!
Exception in thread Thread-1:
Traceback (most recent call last):
  File "threading.py", line 914, in _bootstrap_inner
  File "E:\Users\User1\Downloads\Autopilot\ETS2Autopilot-master\thread_controller.py", line 32, in run
    vjoy = pyvjoy.VJoyDevice(self.vjoy)
AttributeError: module 'pyvjoy' has no attribute 'VJoyDevice'

_Sorry for bad English_

**Comment by xmy0916** [comment]
I use paddlepaddle deep learning framework to achieve driverless driving in this game.
It may help you~
https://github.com/xmy0916/EuroTruckSelfDriver @MiQ12
