### ISSUE TITLE
Ui issues update

### ISSUE THREAD

**Issue by Caleb-J773** [BrunoTh/ETS2Autopilot#3]
Love the UI and ease of use however it comes with a few small issues..

Exception in thread Thread-1:
Traceback (most recent call last):
  File "threading.py", line 914, in _bootstrap_inner
  File "C:\Users\User1\Pictures\ETS2Autopilot-master\ETS2Autopilot-master\thread_controller.py", line 33, in run
    vjoy = pyvjoy.VJoyDevice(self.vjoy)
  File "C:\Users\User1\Pictures\ETS2Autopilot-master\ETS2Autopilot-master\pyvjoy\vjoydevice.py", line 25, in __init__
    _sdk.AcquireVJD(rID)
  File "C:\Users\User1\Pictures\ETS2Autopilot-master\ETS2Autopilot-master\pyvjoy\_sdk.py", line 53, in AcquireVJD
    raise vJoyFailedToAcquireException("Cannot acquire vJoy Device because it is not in VJD_STAT_FREE")
pyvjoy.exceptions.vJoyFailedToAcquireException: Cannot acquire vJoy Device because it is not in VJD_STAT_FREE

*when starting it up ^^

Also the AI doesn't work it just hangs on the tensorflow startup messages. 
after a while it will say 
Exception in thread Thread-3:
Traceback (most recent call last):
  File "threading.py", line 914, in _bootstrap_inner
  File "C:\Users\User1\Pictures\ETS2Autopilot-master\ETS2Autopilot-master\thread_autopilot.py", line 66, in run
    autopilot_button_act = self.joystick.get_button(self.b_autopilot)
pygame.error: joystick system not initialized

**Comment by BrunoTh** [comment]
Thank you.

The first message is known. Have you entered "1" for "vJoy Device" in the settings?

The second message is a bug. Maybe I forgot a line of code or something is in the wrong order. I will do some research for this error.
If the vJoy error is fixed, try it again. Maybe you have to restart the GUI.

**Comment by Caleb-J773** [comment]
Alright i'll try in this in a bit 

Also the UI is cool, needs some work like resolution, about button doesn't work, maybe add some sort of color also maybe have the order be RECORDING, TRAINING, AutoPilot. It would be nice for new users to see like a prompt asking them if they are new to start this process in order.

Otherwise the UI makes things a bit easier

**Comment by BrunoTh** [comment]
Thank you for the feedback. I will realize your suggestions soon.
I know many things don't work yet. I've planned to create an updater to make patching easier.

**Comment by Caleb-J773** [comment]
Traceback (most recent call last):
  File "threading.py", line 914, in _bootstrap_inner
  File "C:\Users\User1\Desktop\ETS2Autopilot-master (1)\ETS2Autopilot-master\thread_autopilot.py", line 66, in run
    autopilot_button_act = self.joystick.get_button(self.b_autopilot)
TypeError: an integer is required (got type str)

^^ I did that "The first message is known. Have you entered "1" for "vJoy Device" in the settings?"

And now I got that message when I attempt to start it up. 

Another random startup error occurred too
`Exception in thread Thread-1:
Traceback (most recent call last):
  File "threading.py", line 914, in _bootstrap_inner
  File "C:\Users\User1\Desktop\ETS2Autopilot-master (1)\ETS2Autopilot-master\thread_controller.py", line 31, in run
    joystick = pygame.joystick.Joystick(self.controller)
TypeError: an integer is required (got type NoneType)

Traceback (most recent call last):
  File "C:\Users\User1\Desktop\ETS2Autopilot-master (1)\ETS2Autopilot-master\UI\main.py", line 160, in enter_mode
    self.thread_autopilot = AutopilotThread(self.ui.statusbar, self.thread_controller, self.ui.steering_wheel, self.ui.image_front)
  File "C:\Users\User1\Desktop\ETS2Autopilot-master (1)\ETS2Autopilot-master\thread_autopilot.py", line 38, in __init__
    self.joystick = pygame.joystick.Joystick(Settings().get_value(Settings.CONTROLLER))
TypeError: an integer is required (got type NoneType)`

**Comment by BrunoTh** [comment]
Are the other values set in the settings? Buttons and axes?
It seems that the values are not stored in the database.

**Comment by Caleb-J773** [comment]
Alright did that but Autopilot is still not working even after turning it on

2017-07-25 07:09:27.452388: W c:\tf_jenkins\home\workspace\release-win\m\windows\py\35\tensorflow\core\platform\cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
2017-07-25 07:09:27.452458: W c:\tf_jenkins\home\workspace\release-win\m\windows\py\35\tensorflow\core\platform\cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use FMA instructions, but these are available on your machine and could speed up CPU computations


^^ just stuck on that

Here's another error message at startup
Exception in thread Thread-1:
Traceback (most recent call last):
  File "threading.py", line 914, in _bootstrap_inner
  File "C:\Users\User1\Desktop\ETS2Autopilot-master (1)\ETS2Autopilot-master\thread_controller.py", line 39, in run
    angle = round((joystick.get_axis(self.axis) + 1) * 32768 / 2)
TypeError: an integer is required (got type str)

**Comment by BrunoTh** [comment]
The first message is okay. It's more an info and the process should be active in background. Do you see something in the status bar of the GUI? Autopilot inactive?

Do avoid the second error: Please download this file (https://www.ets2autopilot.com/thread_controller.py) and move it to the autopilot directory.

**Comment by Caleb-J773** [comment]
Autopilot active but nothing like steering wheel etc. no messages saying that it's "making predictions" I'll go ahead and download that file and see what happens.

**Comment by BrunoTh** [comment]
Yeah. The steering wheel made some trouble so it won't show up. (This is on my TODO-List aswell)
In the background it's making predictions.

**Comment by Caleb-J773** [comment]
Downloaded the file and doesn't seem to be doing nothing to help. Python sometimes crashes when attempting to run the autopilot .

**Comment by BrunoTh** [comment]
Can you edit start_gui.bat and add an "pause" to the end of the file?
With this command the console stays open after python crashes. Does it show an error message?

**Comment by Caleb-J773** [comment]
Exception in thread Thread-26:
Traceback (most recent call last):
  File "threading.py", line 914, in _bootstrap_inner
  File "C:\Users\User1\Desktop\ETS2Autopilot-master (1)\ETS2Autopilot-master\thread_autopilot.py", line 66, in run
    autopilot_button_act = self.joystick.get_button(self.b_autopilot)
pygame.error: Joystick not initialized


Same errors. The autopilot is not working. No steering, Vjoy is acting up too. Half the time doesn't even see my controller.

**Comment by BrunoTh** [comment]
Okay.
I will have a closer look at this problem when I'm at home.

**Comment by BrunoTh** [comment]
Well. I tested the autopilot again with a blank installation. After I set everything up it worked.
Except the autopilot. The steering was strange and I made some changes to thread_controller.py.

My advice: Set up the autopilot from scratch again. Just download the autopilot again (to get the changes I made) and follow the steps on the website.

Please tell me whether it works or not.

**Comment by Caleb-J773** [comment]
It still isn't working. Python stops responding is all the error, adding pause doesn't help. Crashes when you go to record and doesn't seem to be outputting any steering in autopilot mode.

**Comment by BrunoTh** [comment]
Ah! I know this behavior. This happens if you enter the recording mode without having your controller connected.
Have you connected your controller? If yes, go to the settings and check if the selection of the device is right and click save.

**Comment by Caleb-J773** [comment]
Okay that fixes that but it's not outputting any inputs to the steering wheel in game while in autopilot mode.

**Comment by BrunoTh** [comment]
But can you steer using your controller?
If this is the case, is it possible to steer while the autopilot software isn't running?

**Comment by Caleb-J773** [comment]
i can steer only when it's on joy1(aka my controller)

however turn on autopilot and my controller for vjoy works and turns to joy

Also none of the other buttons work in the vjoy.
can't assign accelerate or even turn signals

vjoy seems way to buggy to even be stable anymore.

**Comment by BrunoTh** [comment]
Okay. Then let me explain how the autopilot works:
vJoy is used to pass the predicted steering angle from the autopilot software to ETS2.
If the autopilot is enabled the predicted angle is passed to vJoy. If the autopilot is disabled the signal of your controller is passed to vJoy. This also happens, if the autopilot software is running.
So vJoy is only used for the steering. The other buttons and the throttle axis is used directly from your controller. Thats why you need "Keyboard + vJoy" AND your controller in the ETS2 options.

Please configure the ETS2 controls like I wrote some messages before and try it again. It HAS to work somehow :D

**Comment by Caleb-J773** [comment]
seems like it is working but recording is still not working

Traceback (most recent call last):
  File "C:\Users\User1\Pictures\ETS2Autopilot-master (2)\ETS2Autopilot-master\UI\main.py", line 166, in enter_mode
    self.thread_training = TrainingThread(self.ui.statusbar)
  File "C:\Users\User1\Pictures\ETS2Autopilot-master (2)\ETS2Autopilot-master\thread_training.py", line 14, in __init__
    self.driving_data = DrivingData()
  File "C:\Users\User1\Pictures\ETS2Autopilot-master (2)\ETS2Autopilot-master\driving_data.py", line 64, in __init__
    self.image_list = self.data.get_image_list()
TypeError: get_image_list() missing 1 required positional argument: 'sequence'

**Comment by Caleb-J773** [comment]
![1077](https://user-images.githubusercontent.com/4467576/28694698-213b5026-72f9-11e7-9860-e85af07be26d.png)
it handled this turn pretty well , seems like with your current model it likes to ram the barriers on the side of the highway

**Comment by BrunoTh** [comment]
Thank you very much!
That bug in training mode was serious. I fixed it and now the training works (as far as I tested it).
Please download these three files to the autopilot folder (I really have to implement an updater):
https://raw.githubusercontent.com/BrunoTh/ETS2Autopilot/master/driving_data.py
https://raw.githubusercontent.com/BrunoTh/ETS2Autopilot/master/model.py
https://raw.githubusercontent.com/BrunoTh/ETS2Autopilot/master/thread_training.py

That's nice! Because the model is trained with my images it can be that the autopilot acts different with other settings (FOV, image area, etc.). I have to find a way to normalize the images somehow in future.
Is the subtype of the controller in ETS2 options set to "gamepad"?

**Comment by Caleb-J773** [comment]
Yes it is set to gamepad

**Comment by BrunoTh** [comment]
Okay. Then the model does not work perfectly on your system. The best would be to record and train your own model.

**Comment by Caleb-J773** [comment]
Yep that's what im thinking 👍

**Comment by Caleb-J773** [comment]
![20170726154320_1](https://user-images.githubusercontent.com/4467576/28695905-20d68a04-7300-11e7-9cae-e8b9ed5f080a.jpg)
![20170726154354_1](https://user-images.githubusercontent.com/4467576/28695908-2499348e-7300-11e7-94ac-feecba966ab5.jpg)

this is the ai's truck heh

**Comment by BrunoTh** [comment]
Hehe. I like it :D

**Comment by Caleb-J773** [comment]
Traceback (most recent call last):
  File "C:\Users\User1\Pictures\ETS2Autopilot-master (2)\ETS2Autopilot-master\UI\main.py", line 160, in enter_mode
    self.thread_autopilot = AutopilotThread(self.ui.statusbar, self.thread_controller, self.ui.steering_wheel, self.ui.image_front)
  File "C:\Users\User1\Pictures\ETS2Autopilot-master (2)\ETS2Autopilot-master\thread_autopilot.py", line 42, in __init__
    saver = tf.train.Saver()
  File "C:\Users\User1\Pictures\ETS2Autopilot-master (2)\ETS2Autopilot-master\python\lib\site-packages\tensorflow\python\training\saver.py", line 1139, in __init__
    self.build()
  File "C:\Users\User1\Pictures\ETS2Autopilot-master (2)\ETS2Autopilot-master\python\lib\site-packages\tensorflow\python\training\saver.py", line 1161, in build
    raise ValueError("No variables to save")
ValueError: No variables to save

After training and then turning on autopilot this error shows.

**Comment by Caleb-J773** [comment]
Also my friend is having a issue getting this to work
Traceback (most recent call last):
  File "threading.py", line 914, in _bootstrap_inner
  File "D:\Downloads\Compressed\ETS2Autopilot-master\thread_controller.py", line 32, in run
    vjoy = pyvjoy.VJoyDevice(self.vjoy)
AttributeError: module 'pyvjoy' has no attribute 'VJoyDevice'

get's that when he attempts to train

**Comment by BrunoTh** [comment]
Good point. I've fixed it. Update this file: https://raw.githubusercontent.com/BrunoTh/ETS2Autopilot/master/thread_autopilot.py

The second issue looks for me like your friend hasn't downloaded and extracted pyvjoy into the directory "ETS2Autopilot-master\pyvjoy\"

**Comment by Caleb-J773** [comment]
He already did. 

http://i.imgur.com/KmgmQel.png

That's his folder ^^

Let me try out the fix for my problem with training.

**Comment by Caleb-J773** [comment]
also btw, when does this get lane detection?

**Comment by BrunoTh** [comment]
A lane detection wasn't planned because the AI figures out what to do. Maybe this is a nice to have feature in future.
