### ISSUE TITLE
TypeError: an integer is required (got type NoneType)

### ISSUE THREAD

**Issue by Bluscream** [BrunoTh/ETS2Autopilot#7]
```
C:\Users\blusc\Downloads\ETS2Autopilot-master>python\python.exe start_gui.py
Loading...
Done!
Exception in thread Thread-1:
Traceback (most recent call last):
  File "threading.py", line 914, in _bootstrap_inner
  File "C:\Users\blusc\Downloads\ETS2Autopilot-master\thread_controller.py", line 30, in run
    joystick = pygame.joystick.Joystick(self.controller)
TypeError: an integer is required (got type NoneType)

Traceback (most recent call last):
  File "C:\Users\blusc\Downloads\ETS2Autopilot-master\UI\main.py", line 163, in enter_mode
    self.thread_autopilot = AutopilotThread(self.ui.statusbar, self.thread_controller, self.ui.steering_wheel, self.ui.image_front)
  File "C:\Users\blusc\Downloads\ETS2Autopilot-master\thread_autopilot.py", line 38, in __init__
    self.joystick = pygame.joystick.Joystick(Settings().get_value(Settings.CONTROLLER))
TypeError: an integer is required (got type NoneType)


Press Enter or Esc to close console...
```

---
<a href="https://valid.x86.fr/s1yqi3" style="text-align:center"><img align="center" src="https://valid.x86.fr/cache/banner/s1yqi3-6.png" /></a>

**Comment by BrunoTh** [comment]
You have to open the settings and set everything up first.
The first error message can be ignored.

**Comment by Bluscream** [comment]
which file is the settings?

**Comment by BrunoTh** [comment]
You don't have to edit files. The settings are done in the GUI.
You can open the settings windows in the menu File > Settings.

**Comment by Bluscream** [comment]
And how am i supposed to know what to enter there? It doesnt even have tooltips >.<

**Comment by xmy0916** [comment]
Have you solved it at last？@BrunoTh

**Comment by Bluscream** [comment]
Nope, i never got a response

**Comment by xmy0916** [comment]
I tried this project, but I didn't run it successfully. If there was a picture and text tutorial, it would be great @Bluscream

**Comment by Bluscream** [comment]
same

**Comment by xmy0916** [comment]
@Bluscream I use paddlepaddle deep learning framework to achieve driverless driving in this game.
It may help you~
https://github.com/xmy0916/EuroTruckSelfDriver

**Comment by Bluscream** [comment]
Is there a non-chinese version available?

**Comment by xmy0916** [comment]
When I have finished the whole project, I will write a detailed English description. @Bluscream

**Comment by davidjaksa** [comment]
> And how am i supposed to know what to enter there? It doesnt even have tooltips >.<

I found it, 
File > Settings
